### ISSUE TITLE
API for insertion

### ISSUE THREAD

**Issue by mkremins** [mkremins/fanciful#40]
Example tellraw:

```
/tellraw @a {
  text:"Click.",
  insertion:"Hello there."
}
```

Shift-clicking on the text "Click." will then append the text "Hello there." to the contents of the recipient's chat input box. This feature is apparently similar and orthogonal to `clickEvent` and `hoverEvent`.

**Comment by glen3b** [comment]
How is this different from the existing ´suggest` function, other then corresponding to a different JSON tag?

**Comment by mkremins** [comment]
Insertion differs from suggestion in that suggestions completely replace the text in the chat input box, whereas insertions append to the text that's already been entered. See [this post](http://www.minecraftforum.net/forums/minecraft-discussion/redstone-discussion-and/351959-1-8-raw-json-text-examples-for-tellraw-title-books#ACTIONS) and scroll down to the section about `suggest_command` for details.

**Comment by glen3b** [comment]
OK, I can write code for it later today

**Comment by glen3b** [comment]
You also need to hold shift for insertion to work.

**Comment by glen3b** [comment]
Wrote the code for this in #56
