### ISSUE TITLE
CB-dependent

### ISSUE THREAD

**Issue by jkcclemens** [mkremins/fanciful#45]
Fanciful is currently dependent on CB being used (or its derivatives). It would be immensely useful if this was not the case. I'm not sure if this is at all possible, but removing the need for OBC and NMS imports would be awesome, since plugins using Fanciful could then run on other Bukkit implementations.

**Comment by glen3b** [comment]
As far as GSON shaded in, PR # does this (I think, hard to browse code on phone)

**Comment by glen3b** [comment]
#50. Also, as @mkremins mentioned, CraftBukkit is no longer being actively developed (ATM). This means we definitely need to work on supporting other implementations. If we need to access implementation details, we could build a system where we use different reflections depending on the version string, and then if we don't have a special reflection for a specific version, we default to CB/NMS-based reflection.

**Comment by mkremins** [comment]
This should be fixed as of commit 11a7e606650bf59351b3ebfce2da3af13b7e898b. Since we're now using the standard `/tellraw` command to send messages, we're no longer dependent on any CraftBukkit implementation details.
