### ISSUE TITLE
Can't mvn deploy

### ISSUE THREAD

**Issue by mkremins** [mkremins/fanciful#51]
This isn't an issue in Fanciful per se, but I wanted to document this here in case anyone wonders why the `0.2.1-SNAPSHOT` version of Fanciful isn't yet available from the Maven repo. I'm using GitHub's `site-maven-plugin` to publish artifacts to the `mvn-repo` branch of this repository, and as of today there's [an outstanding issue](https://github.com/github/maven-plugins/issues/69) with `site-maven-plugin` that causes it to crash on attempted deploy unless the user has a publicly visible email address on GitHub.

I don't particularly want to make my email public, especially since there exist outstanding but unmerged fixes for the issue upstream. Until one of those fixes gets merged, or until I figure out another workaround, I won't be able to deploy artifacts to the `mvn-repo` branch.

**Comment by mkremins** [comment]
@franga2000 Could you go ahead and make that pull request? I'll merge ASAP.

**Comment by franga2000** [comment]
Did I not send it? Must have forgot :D Here it is: https://github.com/mkremins/fanciful/pull/54

**Comment by mkremins** [comment]
Merged. Once someone verifies that everything is working, I'll close this issue as well.

**Comment by franga2000** [comment]
I just linked my CI to this repo and it built and deployed successfully: http://ci.franga2000.com/job/Fanciful/15/

Haven't tested it as a dependency, but eveything else on my repo works, so I assume this will too.

**Comment by glen3b** [comment]
Any chance we could set up JavaDoc builds as requested in #32?

**Comment by glen3b** [comment]
Also, the readme is not up to date with the new Maven repo

**Comment by mkremins** [comment]
Just updated the readme. Waiting on the CI to reflect the bunch of commits I just made as a final verification that everything is hooked up correctly; once it does I'll close this issue and we can move the javadoc discussion over to #32.

**Comment by mkremins** [comment]
@franga2000 Hmm, the CI doesn't seem to have picked up the commits. Do I need to change something in this GitHub repository's settings in order to make the post-commit hook work?

**Comment by franga2000** [comment]
Aperently, the CI needs access to the git repo in order to poll it. It was working fine when I was using my fork with my credentials, but now it doesn't have access. I'm trying to find a good and secure way for you to add your credentials to the CI so it can poll the repo. 
Meanwhile, you can create an account on the CI and set your "Full name" field to some random word. Then post that word here, so I know it's you. I'll give you full access to the project so you can trigger builds manually until I get the credentials thing working.

**Comment by mkremins** [comment]
Verifying that I am [username mkremins, fullname Max Kreminski](http://ci.franga2000.com/user/mkremins/) on the CI.

**Comment by franga2000** [comment]
OK, I just gave you full control over the project. You can trigger builds manually and manage the project. I also set it up so it polls git for changes every day and if something's changed, it will build. Hopefully I get the credentias thing sorted out quickly.
