### ISSUE TITLE
Is it possible to use this library to align text in the 1.8 action bar?

### ISSUE THREAD

**Issue by MrSnare** [mkremins/fanciful#58]

**Comment by mkremins** [comment]
Probably not. I've largely stopped playing Minecraft, so I don't know much of anything about action bar text; depending on how much it has in common with ordinary chat messages, I might be willing to accept a pull request that adds an API for styling action bar text.

**Comment by MiniDigger** [comment]
Spigot has it's own api for that stuff now. 
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Player.Spigot.html#sendMessage(net.md_5.bungee.api.ChatMessageType,%20net.md_5.bungee.api.chat.BaseComponent...)
