### ISSUE TITLE
Maven Repo down?

### ISSUE THREAD

**Issue by Baba43** [mkremins/fanciful#64]
Hey, I'm trying to add your great library to my maven project but it seems that the fanciful artifact is missing?

        <repository>
            <id>fanciful-mvn-repo</id>
            <url>http://repo.franga2000.com/artifactory/public</url>
        </repository>
        <dependency>
            <groupId>mkremins</groupId>
            <artifactId>fanciful</artifactId>
            <version>0.3.1</version>
        </dependency>

**Comment by IDragonfire** [comment]
Not found: http://repo.franga2000.com/artifactory/public

**Comment by Lolmewn** [comment]
Just ran into this as well

**Comment by JeromSar** [comment]
Fanciful is licensed under MIT so either way, it's always possible to simply include the project's source manually.

**Comment by Stealth2800** [comment]
Check these two pull requests for alternative repositories @Lolmewn 
https://github.com/mkremins/fanciful/pull/65
https://github.com/mkremins/fanciful/pull/66
